//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Com_i
    {
        public int com_id { get; set; }
        public string cib_s_c { get; set; }
        public string name_of_owner { get; set; }
        public string role { get; set; }
        public string fi { get; set; }
        public string legal { get; set; }
        public Nullable<int> cib_bb_id { get; set; }
        public string stay_order { get; set; }
    }
}
