//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class D_Contract_History
    {
        public int id { get; set; }
        public string Date { get; set; }
        public string Outstanding { get; set; }
        public string Overdue { get; set; }
        public string NPI { get; set; }
        public string Status { get; set; }
        public string Defa { get; set; }
        public Nullable<int> D_id { get; set; }
    }
}
