//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETAILS_OF_INSTALL_Faca
    {
        public int D_id { get; set; }
        public string Ref { get; set; }
        public string FI_code { get; set; }
        public string Branch_code { get; set; }
        public string CIB_contract_code { get; set; }
        public string FI_contract_code { get; set; }
        public string Role { get; set; }
        public string Phase { get; set; }
        public string Facility { get; set; }
        public string Starting_date { get; set; }
        public string End_date_of_contract { get; set; }
        public string Sanction_Limit { get; set; }
        public Nullable<decimal> Total_Disbursement_Amount { get; set; }
        public string Total_number_of_installments { get; set; }
        public Nullable<decimal> Installment_Amount { get; set; }
        public string Remaining_installments_Number { get; set; }
        public Nullable<decimal> Security_Amount { get; set; }
        public string Third_Party_guarantee_Amount { get; set; }
        public string Security_Type { get; set; }
        public string Date_of_Last_Update { get; set; }
        public string Date_of_Law_suit { get; set; }
        public string Date_of_Last_payment { get; set; }
        public string Date_of_classification { get; set; }
        public string Date_of_last_rescheduling { get; set; }
        public string Method_of_payment { get; set; }
        public string Payments_periodicity { get; set; }
        public string Number_of_time_rescheduled { get; set; }
        public string Remaining_installments_Amount { get; set; }
        public string Reorganized_credit { get; set; }
        public string Basis_for_classification_qualitative_judgment { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> cib_bb_id { get; set; }
    }
}
