//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flag
    {
        public int flag_id { get; set; }
        public string table_name { get; set; }
        public string frist_name { get; set; }
        public Nullable<int> frist_flag { get; set; }
        public string second_name { get; set; }
        public Nullable<int> second_flag { get; set; }
        public string third_name { get; set; }
        public Nullable<int> third_flag { get; set; }
    }
}
