//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_ADDRESS
    {
        public int Address_id { get; set; }
        public string Address_Type { get; set; }
        public string Address { get; set; }
        public string Postal_code { get; set; }
        public string District { get; set; }
        public string Country { get; set; }
        public Nullable<int> flag { get; set; }
        public int cib_bb_id { get; set; }
    }
}
