//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_INQUIRED
    {
        public int Inque_id { get; set; }
        public string Trade_name { get; set; }
        public string Proprietorship_District { get; set; }
        public string Proprietorship_Address { get; set; }
        public string Owner_Name { get; set; }
        public string Father_name { get; set; }
        public string Mother_name { get; set; }
        public string DOB { get; set; }
        public string Proprietorship_Postalcode { get; set; }
        public string NID { get; set; }
        public string Owner_Address { get; set; }
        public string Postcode { get; set; }
        public string District { get; set; }
        public string TIN { get; set; }
        public Nullable<int> cib_bb_id { get; set; }
    }
}
