//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMaster
    {
        public int cib_bb_id { get; set; }
        public string CIB_subject_code { get; set; }
        public Nullable<System.DateTime> Date_of_Inquiry { get; set; }
        public string User_ID { get; set; }
        public string FI_Code { get; set; }
        public string Branch_Code { get; set; }
        public string FI_Name { get; set; }
        public string file_location { get; set; }
        public string Upload_date { get; set; }
    }
}
