//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class owner_list
    {
        public int ow_id { get; set; }
        public string cib_sub { get; set; }
        public string Name_owner { get; set; }
        public string Role { get; set; }
        public string stay_order { get; set; }
        public Nullable<int> cib_bb_id { get; set; }
    }
}
