//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROP_CONCERN
    {
        public int linked_id { get; set; }
        public string CIb_sub_Code { get; set; }
        public string Sector_type { get; set; }
        public string Sector_code { get; set; }
        public string Ref_number { get; set; }
        public string Trade_Name { get; set; }
        public string Tele_number { get; set; }
        public Nullable<int> cib_bb_id { get; set; }
    }
}
