//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class REQUESTED_CONTRACT
    {
        public int Req_id { get; set; }
        public Nullable<int> SL { get; set; }
        public string Type_of_Contract { get; set; }
        public string Facility { get; set; }
        public string Phase { get; set; }
        public string Role { get; set; }
        public string FI_Code { get; set; }
        public string Branch_Code { get; set; }
        public string Request_date { get; set; }
        public Nullable<decimal> Total_Requested_Amount { get; set; }
        public string CIB_subject_code { get; set; }
        public string CIB_contract_code { get; set; }
        public string FI_0contract_codede { get; set; }
        public Nullable<int> cib_bb_id { get; set; }
    }
}
