//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sub__INFO
    {
        public int Sub_id { get; set; }
        public string CIB_subject_code { get; set; }
        public string Title_Name { get; set; }
        public string Fathername { get; set; }
        public string SpouseName { get; set; }
        public string Mothername { get; set; }
        public Nullable<System.DateTime> Dob { get; set; }
        public string Gender { get; set; }
        public string District_Country { get; set; }
        public string NID { get; set; }
        public string TIN { get; set; }
        public string Type_of_sub { get; set; }
        public string Ref_number { get; set; }
        public string Sector_type { get; set; }
        public string ID_type { get; set; }
        public string ID_number { get; set; }
        public string ID_issue_date { get; set; }
        public string ID_issue_country { get; set; }
        public string Telephone { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> cib_bb_id { get; set; }
        public string trade_name { get; set; }
        public string sector_code { get; set; }
        public string legal_form { get; set; }
        public string reg_num { get; set; }
        public string reg_date { get; set; }
    
        public virtual Sub__INFO Sub__INFO1 { get; set; }
        public virtual Sub__INFO Sub__INFO2 { get; set; }
    }
}
