//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUM_OF_FACILITY_S_AS_BOR
    {
        public int Bor_id { get; set; }
        public Nullable<int> No_of_reporting_Institutes { get; set; }
        public Nullable<int> No_of_Living_Contracts { get; set; }
        public Nullable<decimal> Total_Outstanding_Amount { get; set; }
        public Nullable<decimal> Total_Overdue_Amount { get; set; }
        public Nullable<int> No_of_Stay_order_contracts { get; set; }
        public Nullable<decimal> Total_Outstanding_amount_for_Stay { get; set; }
        public Nullable<int> cib_bb_id { get; set; }
        public Nullable<int> flag { get; set; }
    }
}
