//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUM_OF_NON_FUNDED_FACILI_AS_BOR
    {
        public int Bor_id { get; set; }
        public string Type_of_Financing { get; set; }
        public Nullable<int> Living_NO { get; set; }
        public Nullable<int> Terminated_NO { get; set; }
        public Nullable<int> Requested_NO { get; set; }
        public Nullable<int> Stay_Order_NO { get; set; }
        public Nullable<decimal> Living_Amount { get; set; }
        public Nullable<decimal> Terminated_Amount { get; set; }
        public Nullable<decimal> Requested_Amount { get; set; }
        public Nullable<decimal> Stay_Order_Amount { get; set; }
        public int cib_bb_id { get; set; }
        public Nullable<int> flag { get; set; }
    }
}
